logging:
  level:
    com.netflix.discovery: ERROR
    com.eca.discovery: INFO
spring:
  application:
    name: ecadiscovery
  profiles:
    active: default
ribbon:
  eureka:
    enabled: true
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URI:http://192.168.196.128:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    hostname: ${EUREKA_HOST_NAME:192.168.196.128}
    preferIpAddress: ${EUREKA_PREFER_IP:false}
    securePortEnabled: false
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health